# Generated by Django 4.0 on 2022-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joboffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comany_name', models.CharField(max_length=60)),
                ('company_email', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=60)),
                ('job_description', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(null=True)),
            ],
        ),
    ]
